Optimize build speed

diff --git a/.github/workflows/detect-ip.yml b/.github/workflows/detect-ip.yml
--- a/.github/workflows/detect-ip.yml
+++ b/.github/workflows/detect-ip.yml
@@ -17,6 +17,10 @@ jobs:
           node-version: 16
 
       - run: |
-          ipis=`{ grep -rn "binbinchengkeyiyou" * || true;}`
-          echo "ipis=$ipis"
-          if [[ -n "$ipis" ]];then echo "有这个值" && grep -rn "binbinchengkeyiyou" * && exit 123; else echo "检查成功"; fi
+          ipis=`{ grep -rn "[1-9]\{2,3\}\.[0-9]\{2,3\}\.[0-9]\{1,3\}.[0-9]\{1,3\}" * || true;}`
+          bdpujesis=`{ grep -rn "bdpujes" * || true;}`
+          bdpdwsis=`{ grep -rn "bdpdws" * || true;}`
+          if [[ -n "$ipis" ]];then echo "$ipis"; fi
+          if [[ -n "$bdpujesis" ]];then echo "$bdpujesis"; fi
+          if [[ -n "$bdpdwsis" ]];then echo "$bdpdwsis"; fi
+          if [[ -n "$bdpdwsis" || -n "$ipis" || -n "$bdpujesis"]];then echo "check error!" && exit 123; else echo "check success"; fi
